// <auto-generated />
namespace CrazyAppsStudio.Delegacje.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class expensedocumenttypesmovedtodb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expensedocumenttypesmovedtodb));
        
        string IMigrationMetadata.Id
        {
            get { return "201512142220050_expense-document-types-moved-to-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
